# default configure
app:
  port: 3000
  log_level: debug
  crontime: "* * * * *"

uptimerobot:
  api_key:
  pattern: "%group/%name"
  statuses: "2-9"

website:
  title: "Service Status"
  copyright: ""
 # links:
  #  - name: Home
 #     href: https://uptimerobot.com
 #   - name: GitHub
  #    href: https://github.com/giuem/uptimerobot-page
